apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: mlops-web-deployment 
  labels: 
    app: mlops-web 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mlops-web 
  template: 
    metadata: 
      labels: 
        app: mlops-web 
    spec: 
      containers: 
      - name: mlops-web 
        image: gcr.io/mlops-prac-476507/mlops-web:latest # <--- RUTA DE IMAGEN 
        ports: 
        - containerPort: 8501 
        env: 
        - name: API_URL_PREDICT 
          value: http://mlops-api-pf-service:5000/predict # <--- Conexión al servicio interno de la API 
        - name: API_URL_XAI 
          value: http://mlops-api-pf-service:5000/xai_example # <--- Conexión al servicio interno de la API
        - name: API_URL_EVALUATE 
          value: http://mlops-api-pf-service:5000/evaluate_model # <--- Conexión al servicio interno de la API
        - name: API_URL_FEATURES 
          value: http://mlops-api-pf-service:5000/feature_names # <--- Conexión al servicio interno de la API
        - name: API_URL_RETRAIN 
          value: http://mlops-api-pf-service:5000/retrain # <--- Conexión al servicio interno de la API